#include "constexpr/enum.hpp"

#include <gtest/gtest.h>

#include <cstdint>
#include <random>
#include <sstream>
#include <string>
#include <string_view>

namespace {

using Constexpr::eEnumStorageType;

/**
 * @brief Number of random raw programs generated by each fuzz test.
 *
 * The value is fixed so the test remains deterministic and does not make the
 * normal test suite unnecessarily slow.
 */
constexpr std::uint32_t kRandomProgramCount{5000u};

/**
 * @brief Number of mutated valid programs generated by the mutation test.
 *
 * Mutated valid programs are more expensive than raw byte streams because some
 * mutations still decode and then exercise the render path.
 */
constexpr std::uint32_t kRandomMutationCount{2000u};

/**
 * @brief Maximum byte length used for random raw enum programs.
 *
 * This keeps generated programs small enough to focus on opcode, string,
 * mask, continuation, and truncation boundaries.
 */
constexpr std::size_t kMaxRandomProgramBytes{64u};

/**
 * @brief Number of random uint16_t values rendered after a successful decode.
 *
 * Rendering all 65536 uint16_t values for every successful random decode is too
 * expensive for a normal unit test, so this uses deterministic samples.
 */
constexpr std::uint32_t kUint16RenderSampleCount{128u};

/**
 * @brief Returns the expected one-byte storage header for one value type.
 *
 * @tparam ValueT - Enum or integral value type.
 * @param compress - Whether to set the stream compression flag.
 * @return std::uint8_t - Header byte used by decoded enum programs.
 */
template <typename ValueT>
constexpr std::uint8_t storage_header_for(bool compress = false)
{
  auto header{
    static_cast<std::uint8_t>(
      Constexpr::impl::storage_type_for_value_type<ValueT>())
  };
  if (compress) {
    header = static_cast<std::uint8_t>(
      header | static_cast<std::uint8_t>(eEnumStorageType::Compress));
  }
  return header;
}

/**
 * @brief Creates a string view over a byte string.
 *
 * The enum program format can contain embedded NUL bytes, so tests must always
 * preserve the explicit byte count.
 *
 * @param program - Byte program stored in a std::string.
 * @return std::string_view - View over every stored byte.
 */
std::string_view program_view(std::string const& program)
{
  return std::string_view{ program.data(), program.size() };
}

/**
 * @brief Renders one enum value through the public stream API.
 *
 * This checks externally observable behaviour instead of inspecting internal
 * enum graph storage.
 *
 * @tparam EnumT - Enum description type.
 * @param enum_def - Enum definition used to render the value.
 * @param value - Runtime value to render.
 * @return std::string - Rendered enum text.
 */
template <typename EnumT>
std::string render_enum_value(
  EnumT const& enum_def,
  typename EnumT::value_type value)
{
  std::ostringstream stream{};
  stream << enum_def(value);
  return stream.str();
}

/**
 * @brief Decodes a headered enum program using the public builder API.
 *
 * @tparam Settings - Enum settings used by the decoded enum.
 * @param program - Headered enum program bytes.
 * @return Constexpr::Enum<Settings> - Decoded enum definition.
 */
template <typename Settings>
Constexpr::Enum<Settings> decode_program(std::string_view program)
{
  return Constexpr::build_enum_description<Settings>()
    .decode_program(program)
    .Build();
}

/**
 * @brief Converts a constexpr string result to a std::string.
 *
 * The mutation tests need mutable byte storage, so generated enum programs are
 * copied out of the fixed-capacity constexpr string container.
 *
 * @tparam ProgramT - Program string container type.
 * @param program - Program returned by output_program().
 * @return std::string - Mutable byte copy preserving embedded NUL bytes.
 */
template <typename ProgramT>
std::string to_std_string(ProgramT const& program)
{
  auto const view{ static_cast<std::string_view>(program) };
  return std::string{ view.data(), view.size() };
}

/**
 * @brief Generates an unconstrained random byte program.
 *
 * @param rng - Deterministic random number generator.
 * @param max_size - Maximum generated byte count.
 * @return std::string - Random byte program.
 */
std::string random_byte_program(std::mt19937_64& rng, std::size_t max_size)
{
  std::uniform_int_distribution<std::size_t> size_dist{ 0u, max_size };
  std::uniform_int_distribution<unsigned> byte_dist{ 0u, 255u };

  std::string program{};
  auto const size{ size_dist(rng) };
  program.reserve(size);
  for (std::size_t i{0u}; i < size; ++i) {
    program.push_back(static_cast<char>(byte_dist(rng)));
  }
  return program;
}

/**
 * @brief Generates a random program with a valid storage header.
 *
 * The payload remains random, which exercises decoder opcode and structure
 * validation after the storage-header gate succeeds.
 *
 * @tparam ValueT - Enum or integral value type used by the header.
 * @param rng - Deterministic random number generator.
 * @param compress - Whether to use the compressed stream header.
 * @param max_payload_size - Maximum generated payload byte count.
 * @return std::string - Headered random byte program.
 */
template <typename ValueT>
std::string random_headered_program(
  std::mt19937_64& rng,
  bool compress,
  std::size_t max_payload_size)
{
  auto program{ random_byte_program(rng, max_payload_size) };
  program.insert(
    program.begin(),
    static_cast<char>(storage_header_for<ValueT>(compress)));
  return program;
}

/**
 * @brief Mutates one valid program by flipping, inserting, or erasing bytes.
 *
 * @param program - Valid program to mutate.
 * @param rng - Deterministic random number generator.
 * @return std::string - Mutated byte program.
 */
std::string mutate_program(std::string program, std::mt19937_64& rng)
{
  std::uniform_int_distribution<unsigned> operation_dist{ 0u, 2u };
  std::uniform_int_distribution<unsigned> byte_dist{ 0u, 255u };
  std::uniform_int_distribution<std::size_t> count_dist{ 1u, 4u };

  auto const mutation_count{ count_dist(rng) };
  for (std::size_t i{0u}; i < mutation_count; ++i) {
    auto const operation{ operation_dist(rng) };
    if (operation == 0u && !program.empty()) {
      std::uniform_int_distribution<std::size_t> pos_dist{
        0u,
        program.size() - 1u
      };
      auto const pos{ pos_dist(rng) };
      program[pos] = static_cast<char>(byte_dist(rng));
    }
    else if (operation == 1u) {
      std::uniform_int_distribution<std::size_t> pos_dist{
        0u,
        program.size()
      };
      auto const pos{ pos_dist(rng) };
      program.insert(program.begin() + static_cast<std::ptrdiff_t>(pos),
        static_cast<char>(byte_dist(rng)));
    }
    else if (!program.empty()) {
      std::uniform_int_distribution<std::size_t> pos_dist{
        0u,
        program.size() - 1u
      };
      auto const pos{ pos_dist(rng) };
      program.erase(program.begin() + static_cast<std::ptrdiff_t>(pos));
    }
  }
  return program;
}

/**
 * @brief Decodes a program or accepts a documented enum parse failure.
 *
 * If the program decodes successfully, every uint8_t value is rendered to prove
 * that the decoder did not create an invalid internal graph.
 *
 * @tparam Settings - uint8_t enum settings used for the decoded enum.
 * @param program - Candidate headered enum program.
 * @return bool - True when the candidate decoded successfully.
 */
template <typename Settings>
bool decode_or_accept_parse_failure_for_uint8(std::string_view program)
{
  static_assert(std::is_same_v<typename Settings::value_type, std::uint8_t>,
    "This helper renders every uint8_t value.");

  std::vector<std::string> strs{};
  strs.reserve(256);
  try {
    auto const decoded{ decode_program<Settings>(program) };
    for (std::uint16_t i{0u}; i <= std::uint16_t{255u}; ++i) {
      strs.push_back("boo");
      auto s = render_enum_value(decoded, static_cast<std::uint8_t>(i));
      if (s != "") {
        strs.back() = std::move(s);
      }
    }

    auto const reencoded{ decoded.output_program(false, false) };
    auto const redecode{ decode_program<Settings>(reencoded) };
    for (std::uint16_t i{0u}; i <= std::uint16_t{255u}; ++i) {
      auto const value{ static_cast<std::uint8_t>(i) };
      EXPECT_EQ(render_enum_value(redecode, value),
        render_enum_value(decoded, value)) << "value " << i;
    }
    return true;
  }
  catch (Constexpr::EnumParseError const&) {
    return false;
  }
}

/**
 * @brief Decodes a program or accepts a documented enum parse failure.
 *
 * If the compressed uint16_t program decodes, deterministic sample values are
 * rendered and the decoded graph is re-encoded and decoded again.
 *
 * @tparam Settings - uint16_t enum settings used for the decoded enum.
 * @param program - Candidate headered enum program.
 * @param rng - Deterministic random number generator for render samples.
 * @return bool - True when the candidate decoded successfully.
 */
template <typename Settings>
bool decode_or_accept_parse_failure_for_uint16(
  std::string_view program,
  std::mt19937_64& rng)
{
  static_assert(std::is_same_v<typename Settings::value_type, std::uint16_t>,
    "This helper renders sampled uint16_t values.");

  try {
    auto const decoded{ decode_program<Settings>(program) };
    std::uniform_int_distribution<unsigned> value_dist{ 0u, 65535u };
    for (std::uint32_t i{0u}; i < kUint16RenderSampleCount; ++i) {
      auto const value{ static_cast<std::uint16_t>(value_dist(rng)) };
      (void)render_enum_value(decoded, value);
    }

    auto const reencoded{ decoded.output_program(true, false) };
    auto const redecode{ decode_program<Settings>(reencoded) };
    for (std::uint32_t i{0u}; i < kUint16RenderSampleCount; ++i) {
      auto const value{ static_cast<std::uint16_t>(value_dist(rng)) };
      EXPECT_EQ(render_enum_value(redecode, value),
        render_enum_value(decoded, value)) << "value " << value;
    }
    return true;
  }
  catch (Constexpr::EnumParseError const&) {
    return false;
  }
}

/**
 * @brief Builds a valid uint8_t seed program for mutation fuzzing.
 *
 * The seed contains names, a numeric field, and a conditional so mutation can
 * disturb several different command encodings.
 *
 * @return std::string - Valid uncompressed uint8_t enum program.
 */
std::string make_valid_uint8_seed_program()
{
  using Settings = Constexpr::EnumSettings<
    std::uint8_t,
    Constexpr::pack_space(512, 256)
  >;

  auto const enum_def{
    Constexpr::build_enum_description<Settings>()
      .Named(std::uint8_t{0x00u}, "zero")
      .Named(std::uint8_t{0x01u}, "one")
      .Named(std::uint8_t{0x02u}, "two")
      .Numeric(
        std::uint8_t{0x30u},
        "field",
        Constexpr::eEnumCommand::fRightShiftBits)
      .If(std::uint8_t{0x80u}, std::uint8_t{0x0Fu})
        .Named(std::uint8_t{0x01u}, "if-one")
      .Else()
        .Named(std::uint8_t{0x00u}, "else-zero")
        .Named(std::uint8_t{0x04u}, "else-four")
      .End()
      .Build()
  };

  return to_std_string(enum_def.output_program(false, false));
}

} // namespace

/**
 * @brief Fuzzes fully random uint8_t byte streams.
 *
 * Each candidate must either throw a documented enum parse error or decode into
 * an enum graph that can render every uint8_t value and survive re-encoding.
 */
TEST(EnumRandomFuzz, RandomUint8ByteStreamsRejectOrRenderSafely)
{
  using Settings = Constexpr::EnumSettings<
    std::uint8_t,
    Constexpr::pack_space(2048, 2048)
  >;

  std::mt19937_64 rng{0x8a72'1800'5147'9b3dull};
  std::uint32_t decoded_count{0u};

  for (std::uint32_t i{0u}; i < kRandomProgramCount; ++i) {
    SCOPED_TRACE(i);
    auto const program{ random_byte_program(rng, kMaxRandomProgramBytes) };
    if (decode_or_accept_parse_failure_for_uint8<Settings>(
      program_view(program))) {
      ++decoded_count;
    }
  }

  (void)decoded_count;
}

/**
 * @brief Fuzzes uint8_t streams that have a valid storage header.
 *
 * A valid header bypasses the first decode gate so random payload bytes exercise
 * opcode, mask, string, branch, and continuation validation more often.
 */
TEST(EnumRandomFuzz, HeaderedRandomUint8PayloadsRejectOrRenderSafely)
{
  using Settings = Constexpr::EnumSettings<
    std::uint8_t,
    Constexpr::pack_space(2048, 2048)
  >;

  std::mt19937_64 rng{0x4c91'00a2'77d3'401full};
  std::uint32_t decoded_count{0u};

  for (std::uint32_t i{0u}; i < kRandomProgramCount; ++i) {
    SCOPED_TRACE(i);
    auto const program{
      random_headered_program<std::uint8_t>(
        rng,
        false,
        kMaxRandomProgramBytes)
    };
    if (decode_or_accept_parse_failure_for_uint8<Settings>(
      program_view(program))) {
      ++decoded_count;
    }
  }

  EXPECT_GT(decoded_count, 0u);
}

/**
 * @brief Fuzzes byte mutations of one valid uint8_t enum program.
 *
 * Mutations that become invalid must throw parse errors.  Mutations that remain
 * valid must render safely for all uint8_t values and survive re-encoding.
 */
TEST(EnumRandomFuzz, MutatedValidUint8ProgramsRejectOrRenderSafely)
{
  using Settings = Constexpr::EnumSettings<
    std::uint8_t,
    Constexpr::pack_space(2048, 2048)
  >;

  auto const seed_program{ make_valid_uint8_seed_program() };
  std::mt19937_64 rng{0x17d2'f395'ab6c'8041ull};
  std::uint32_t decoded_count{0u};

  ASSERT_TRUE(decode_or_accept_parse_failure_for_uint8<Settings>(
    program_view(seed_program)));

  for (std::uint32_t i{0u}; i < kRandomMutationCount; ++i) {
    SCOPED_TRACE(i);
    auto const program{ mutate_program(seed_program, rng) };
    if (decode_or_accept_parse_failure_for_uint8<Settings>(
      program_view(program))) {
      ++decoded_count;
    }
  }

  EXPECT_GT(decoded_count, 0u);
}

/**
 * @brief Fuzzes compressed uint16_t streams with random payloads.
 *
 * The compressed-header path exercises condensed integer decoding.  Successful
 * decodes are rendered with deterministic uint16_t sample values and then
 * re-encoded with compression enabled.
 */
TEST(EnumRandomFuzz, HeaderedRandomCompressedUint16PayloadsRejectOrRenderSafely)
{
  using Settings = Constexpr::EnumSettings<
    std::uint16_t,
    Constexpr::pack_space(2048, 2048)
  >;

  std::mt19937_64 rng{0xf05d'2b2c'091e'447bull};
  std::uint32_t decoded_count{0u};

  for (std::uint32_t i{0u}; i < kRandomProgramCount; ++i) {
    SCOPED_TRACE(i);
    auto const program{
      random_headered_program<std::uint16_t>(
        rng,
        true,
        kMaxRandomProgramBytes)
    };
    if (decode_or_accept_parse_failure_for_uint16<Settings>(
      program_view(program),
      rng)) {
      ++decoded_count;
    }
  }

  EXPECT_GT(decoded_count, 0u);
}
